name: vina
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - alabaster=1.0.0=pyhd8ed1ab_1
  - babel=2.17.0=pyhd8ed1ab_0
  - biopython=1.86=py311h3485c13_0
  - boost-cpp=1.84.0=hce07faa_7
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py311h69b5583_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.0=h32b962e_3
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h3fd045d_3
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - expat=2.7.3=h9214b88_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gemmi=0.7.3=py311hf723e3d_2
  - greenlet=3.2.4=py311h3e6a449_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libboost=1.84.0=hb0986bb_7
  - libboost-devel=1.84.0=h91493d7_7
  - libboost-headers=1.84.0=h57928b3_7
  - libboost-python=1.84.0=py311h9b10771_7
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libcufft=11.4.1.4=hac47afa_1
  - libdeflate=1.25=h51727cc_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.84.4=hfaec014_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libpq=16.10=h18d9880_2
  - librdkit=2024.03.6=h4c5bbc8_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-base=3.10.7=py311h1675fdf_0
  - meeko=0.7.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=1.26.4=py311h0b4df5a_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.4=h24db6dd_0
  - openmm=8.4.0=py311h3fb64e9_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pcre2=10.46=h3402e2f_0
  - pdbfixer=1.12=pyhd8ed1ab_0
  - pillow=12.0.0=py311hf7ee305_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - prody=2.4.1=pyh5e1b82b_2
  - pthread-stubs=0.4=h0e40799_1002
  - pycairo=1.27.0=py311ha86e5f0_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - reportlab=4.4.4=py311h3485c13_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinx_rtd_theme=3.0.2=pyha770c72_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jquery=4.1=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlalchemy=2.0.44=py311h3485c13_0
  - sqlite=3.50.2=hda9a48d_1
  - swig=4.4.0=h8081d6d_1
  - tbb=2022.3.0=hd094cb3_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py311h3485c13_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zlib=1.3.1=h02ab6af_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.25.0=py311hf893f09_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - rdkit==2025.9.1
      - rich==14.2.0
      - scipy==1.16.3
